# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5ae65be6213c3e8acffc893e610bb7d9fe5149e73715cd5ec36a9169e04652d3fe0c89563f3a3b2de86a4d08ae6418ab4aea6ba0a3f6fa97b7ce757bde0f82b

test:
  secret_key_base: 47a111b6c254b068a77e3843bb816486a5821b689c0e1c61416ce6048ccc1e17120a124b3166d4a889fc27c0ca70ea9c3e1c84b1c098fb183dcf11926c5cb01d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
